USE `@DB-NAME@`;

-- Add new JbpmTaskInstance fields
ALTER TABLE JBPM_TASKINSTANCE ADD COLUMN `LASTOPENED_` datetime DEFAULT NULL AFTER `DUEDATE_`;
ALTER TABLE JBPM_TASKINSTANCE ADD COLUMN `LASTSAVED_` datetime DEFAULT NULL AFTER `LASTOPENED_`;
ALTER TABLE JBPM_TASKINSTANCE ADD COLUMN `TIMEWORKEDON_` bigint DEFAULT NULL AFTER `LASTSAVED_`;

-- Set a sensible default value
UPDATE JBPM_TASKINSTANCE SET `TIMEWORKEDON_` = 0 WHERE `TIMEWORKEDON_` IS NULL;
