USE `@DB-NAME@`;
select (@super:=id) from role where name = 'superadmin';
select (@admin:=id) from role where name = 'admin';
select (@man:=id) from role where name = 'manager';
select (@ann:=id) from role where name = 'annotator';
ALTER TABLE annotation_service ADD COLUMN can_use_private_urls char(1) DEFAULT NULL;

-- Guess sensible values for existing services.  Services whose URLs are
-- relative to the installation (i.e. start with a slash) are assumed to be
-- able to use private URLs, and all other services are assumed not to.
UPDATE annotation_service SET can_use_private_urls = 'Y' WHERE url LIKE '/%';
UPDATE annotation_service SET can_use_private_urls = 'N' WHERE can_use_private_urls IS NULL;

-- Map the old separated services to their new endpoints under common-services
UPDATE annotation_service SET url = '/common-services/services/copy'
  WHERE url = '/copy-service/services/GATEService';

UPDATE annotation_service SET url = '/common-services/services/merge'
  WHERE url = '/merging-service/services/GATEService';

UPDATE annotation_service SET url = '/common-services/services/annie'
  WHERE url = '/annie-service/services/GATEService';

UPDATE annotation_service SET url = '/common-services/services/reset'
  WHERE url = '/reset-service/services/GATEService';

UPDATE annotation_service
  SET url = '/common-services/services/ast',
      parameters = '<map><entry><string>parameterValue</string><string></string></entry><entry><string>parameterKey</string><string></string></entry><entry><string>asExtraMappings</string><string>in=safe.preprocessing</string></entry><entry><string>asKey</string><string>out</string></entry><entry><string>asValue</string><string></string></entry></map>'
  WHERE url = '/ml-service/services/application';

-- Rename the old preprocessing service to indicate that it's disabled.
-- We can't delete it entirely in case it's referenced from existing projects.
UPDATE annotation_service
  SET name = 'DISABLED pre-processing gas',
      description = 'The pre-processing service is no longer available.  You should remove all references to this service from your projects and workflow templates, and then delete this service definition.'
  WHERE url = '/preprocessing-service/services/GATEService';

-- Add schema-aware pre-manual GAS
select (@gas:=id) from annotation_service_type where name = 'gas';
INSERT INTO annotation_service
    (`name`, `url`, `description`, `parameters`,
     `annotation_service_type_id`, `can_use_private_urls`)
  VALUES
  ('example schema-aware pre-manual gas',
   '/common-services/services/schema-cleaner',
   'GAS for preparing manual annotation task, only copies annotations from the preprocessing set that are valid according to the specified schemas',
   '<map><entry><string>parameterValue</string><string>Person, Location, Organization</string></entry><entry><string>parameterKey</string><string>schemas</string></entry><entry><string>asExtraMappings</string><string>in=safe.preprocessing</string></entry><entry><string>asKey</string><string>out</string></entry><entry><string>asValue</string><string></string></entry></map>',
   @gas,
   'Y');

-- Add salt and iterations columns to app_user.  Existing passwords have no
-- salt and one iteration so they continue to work as before.
ALTER TABLE app_user ADD COLUMN `salt` varchar(255) DEFAULT NULL AFTER `password`;
ALTER TABLE app_user ADD COLUMN `iterations` int(11) DEFAULT NULL AFTER `salt`;
UPDATE app_user SET iterations = 1 WHERE iterations IS NULL;

-- fix up resource/role mappings
DELETE FROM `resource`;
INSERT INTO `resource` (`id`,`url`,`description`,`service_id`) VALUES
 (1, '/aMenu.html*','Admin Menu',1),
 (2, '/activeUsers.html*','list all active users',1),
 (3, '/roles.html*','Roles List Page',1),
 (4, '/editRole.html*','Edit Role',1),
 (5, '/reload.html*','Reload Page',1),
 (6, '/flush.html*','Flush Cache Page',1),
 (7, '/clickstreams.jsp*','Click Streams Page',1),
 (8, '/resources.html*','Resources List Page',1),
 (9, '/services.html*','Services List',1),
 (10, '/resourceMenu.html*','Resource Menu',7),
 (11, '/annotationServices.html*','Annotation Services',7),
 (12, '/annotationServiceInfo.html*','Annotation Service Info',7),
 (13, '/popupAnnotationServiceInfo.html*','Annotation Service Info',7),
 (14, '/editAnnotationService.html*','Edit Annotation Service',7),
 (15, '/saveAnnotationService.html*','Save Annotation Service',7),
 (16, '/popupAddAnnotationService.html*','Add Annotation Service',7),
 (17, '/schemas.html*','Annotation Schemas',7),
 (18, '/addSchema.html*','Add annotation schema',7),
 (19, '/popupAddSchema.html*','Add annotation schema',7),
 (20, '/schemaUploadInfo.html*','Schema upload info page',7),
 (21, '/popupSchemaUploadInfo.html*','Schema upload info page',7),
 (22, '/annotator-gui/*','Annotator GUI URL',7),
 (23, '/mainMenu.html*','Main Menu Page',3),
 (24, '/helpInfo.html*','Help Page',4),
 (25, '/forum.html*','Forum',4),
 (26, '/supportMenu.html*','Support Menu',3),
 (27, '/chat.html*','Chat',4),
 (28, '/scripts/util.jsp*','DWR Util Page',3),
 (29, '/scripts/engine.jsp*','Engine Page',3),
 (30, '/download.html*','Download',4),
 (31, '/adm*','Forum Administration',4),
 (32, '/corpora.html*','DocService Home Page',5),
 (33, '/editUploadCorpus.html*','Upload Corpus',5),
 (34, '/saveUploadCorpus.html*','Upload Corpus',5),
 (35, '/corpusUploadInfo.html*','Corpus upload info',5),
 (36, '/popupCorpusUploadInfo.html*','Corpus upload info',5),
 (37, '/saveCorpus.html*','Save Corpus',5),
 (38, '/documentsInCorpus.html*','Documents in corpus',5),
 (39, '/datastore.html*','Download Datastore',5),
 (40, '/corpus.html*','Download Corpus',5),
 (41, '/annicgui.html*','ANNIC GUI',5),
 (42, '/viewDocument.html*','View document in annotator GUI',5),
 (43, '/annotatorGui.html*','Launch pool-mode Annotator GUI',5),
 (44, '/ontologyRepositoryList.html*','Ontology Repository List',8),
 (45, '/addOntologyRepository.html*','Add Ontology Repository',8),
 (46, '/editProfile.html*','User Profile Edit Page',2),
 (47, '/passwordHint.html*','Password Hint Page',2),
 (48, '/signup.html*','SignUp Page',2),
 (49, '/users.html*','Users List Page',2),
 (50, '/editUser.html*','Users Edit Page',2),
 (51, '/bulkUpload.html*','Bulk upload form',2),
 (52, '/bulkSave.html*','Bulk upload target',2),
 (53, '/processDefinitionList.html?method=list*','Process Definitions List Page',6),
 (54, '/processDefinitionUpload.html*','Upload Process Definition',6),
 (55, '/processInstanceList.html*','Process Instance List Page',6),
 (56, '/processInstanceList.html?method=listAll*','Running Projects',6),
 (57, '/editActors.html*','Edit actors for process instance',6),
 (58, '/saveActors.html*','Save actors for process instance',6),
 (59, '/taskInstanceList.html?method=list*','Task Instance List Page',6),
 (60, '/taskInstanceList.html?method=listByActor*','Pending Task Instance Page',6),
 (61, '/workflowMenu.html*','Work Flow Home Page',6),
 (62, '/editProject.html*','Edit Project',6),
 (63, '/loadProject.html?method=load*','New Process Instance',6),
 (64, '/projects.html*','Workflow Templates',6),
 (65, '/projects.html?method=listAll*','All Workflow Templates',6),
 (66, '/**/*.html*','All the Pages',3);

DELETE FROM `resource_role`;
INSERT INTO `resource_role` (`resource_id`,`role_id`) VALUES 
 (1,@super),
 (1,@admin),
 (2,@super),
 (2,@admin),
 (2,@man),
 (3,@super),
 (4,@super),
 (5,@super),
 (5,@admin),
 (6,@super),
 (6,@admin),
 (7,@super),
 (7,@admin),
 (8,@super),
 (9,@super),
 (10,@super),
 (10,@admin),
 (10,@man),
 (11,@super),
 (11,@admin),
 (11,@man),
 (12,@super),
 (12,@admin),
 (12,@man),
 (13,@super),
 (13,@admin),
 (13,@man),
 (14,@super),
 (14,@admin),
 (14,@man),
 (15,@super),
 (15,@admin),
 (15,@man),
 (16,@super),
 (16,@admin),
 (16,@man),
 (17,@super),
 (17,@admin),
 (17,@man),
 (18,@super),
 (18,@admin),
 (18,@man),
 (19,@super),
 (19,@admin),
 (19,@man),
 (20,@super),
 (20,@admin),
 (20,@man),
 (21,@super),
 (21,@admin),
 (21,@man),
 (22,@ann),
 (23,@super),
 (23,@admin),
 (23,@man),
 (23,@ann),
 (24,@super),
 (24,@admin),
 (24,@man),
 (24,@ann),
 (25,@super),
 (25,@admin),
 (25,@man),
 (25,@ann),
 (26,@super),
 (26,@admin),
 (26,@man),
 (26,@ann),
 (27,@super),
 (27,@admin),
 (27,@man),
 (27,@ann),
 (28,@super),
 (28,@admin),
 (28,@man),
 (28,@ann),
 (29,@super),
 (29,@admin),
 (29,@man),
 (29,@ann),
 (30,@super),
 (30,@admin),
 (30,@man),
 (30,@ann),
 (31,@super),
 (31,@admin),
 (32,@super),
 (32,@admin),
 (32,@man),
 (33,@super),
 (33,@admin),
 (33,@man),
 (34,@super),
 (34,@admin),
 (34,@man),
 (35,@super),
 (35,@admin),
 (35,@man),
 (36,@super),
 (36,@admin),
 (36,@man),
 (37,@super),
 (37,@admin),
 (37,@man),
 (38,@super),
 (38,@admin),
 (38,@man),
 (39,@super),
 (39,@admin),
 (39,@man),
 (40,@super),
 (40,@admin),
 (40,@man),
 (41,@super),
 (41,@admin),
 (41,@man),
 (42,@super),
 (42,@admin),
 (42,@man),
 (43,@super),
 (43,@admin),
 (43,@man),
 (43,@ann),
 (44,@super),
 (44,@admin),
 (45,@super),
 (45,@admin),
 (46,@super),
 (46,@admin),
 (46,@man),
 (46,@ann),
 (47,@super),
 (47,@admin),
 (47,@man),
 (47,@ann),
 (48,@super),
 (48,@admin),
 (48,@man),
 (48,@ann),
 (49,@super),
 (49,@admin),
 (50,@super),
 (50,@admin),
 (51,@super),
 (51,@admin),
 (52,@super),
 (52,@admin),
 (53,@super),
 (54,@super),
 (55,@super),
 (55,@admin),
 (55,@man),
 (56,@super),
 (56,@admin),
 (56,@man),
 (57,@super),
 (57,@admin),
 (57,@man),
 (58,@super),
 (58,@admin),
 (58,@man),
 (59,@super),
 (59,@admin),
 (59,@man),
 (60,@super),
 (60,@admin),
 (60,@man),
 (61,@super),
 (61,@admin),
 (61,@man),
 (62,@super),
 (62,@admin),
 (62,@man),
 (63,@super),
 (63,@admin),
 (63,@man),
 (64,@super),
 (64,@admin),
 (64,@man),
 (65,@super),
 (65,@admin),
 (65,@man),
 (66,@super),
 (66,@admin),
 (66,@man),
 (66,@ann);
