#!/bin/sh
#
# init.d-style script to start and stop GATE Service workers

PROG="GATE Service Workers"

# Edit this if jsvc (Apache commons daemon) is not on your PATH
JSVC=jsvc

# Uncomment this if JAVA_HOME is not set appropriately already
#JAVA_HOME=/Library/Java/Home

# PID file - change this if you don't have write access to /var/run
PIDFILE=/var/run/gate-service.pid

# Log file - change this if you don't have write access to /var/log
LOGFILE=/var/log/gate-service.log

# The following should make a good guess at the location of the GaS files, but
# you may need to override it
GAS_HOME=`dirname $0`

# If you are running this script as root, uncomment this and set it to the user
# name under which the workers should run.
#USER=tomcat

if [ -n "$USER" ]; then
  USERFLAG="-user $USER"
fi

cd $GAS_HOME

jsvc_classpath=gate-service/classes:`echo lib/*.jar | tr ' ' ':'`

start() {
  echo -n "Starting $PROG..."
  $JSVC -home "$JAVA_HOME" \
        $USERFLAG \
        -pidfile "$PIDFILE" \
        -cp "$jsvc_classpath" \
        -outfile "$LOGFILE" \
        -errfile '&1' \
        -wait 120 \
        -Djava.awt.headless=true \
        -Dgleam.gateservice.top.dir="$GAS_HOME/gate-service" \
        -Dlog4j.configuration=log4j-config.properties \
        gleam.gateservice.worker.WorkerRunner \
        gate-service/spring/*.xml \
  && echo "done" || echo "error: $?"
}

stop() {
  echo -n "Stopping $PROG (PID `cat $PIDFILE`)..."
  $JSVC -home "$JAVA_HOME" \
        $USERFLAG \
        -pidfile "$PIDFILE" \
        -cp "$jsvc_classpath" \
        -wait 120 \
        -Djava.awt.headless=true \
        -stop \
        gleam.gateservice.worker.WorkerRunner \
  && echo "done" || echo "error: $?"
}

status() {
  $JSVC -home "$JAVA_HOME" \
        $USERFLAG \
        -pidfile "$PIDFILE" \
        -cp "$jsvc_classpath" \
        -wait 120 \
        -Djava.awt.headless=true \
        -check \
        gleam.gateservice.worker.WorkerRunner
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart}"
    exit 1
esac

exit 0
